#!/usr/bin/env fish

ln -s ~/.sys-config/vim/ ~/.vim
ln -s ~/.sys-config/vim/vimrc ~/.vimrc

ln -s ~/.sys-config/zshrc ~/.zshrc

ln -s ~/.sys-config/gitignore ~/.gitignore
git config --global core.excludesfile ~/.gitignore

ln -s ~/.sys-config/tmux.conf ~/.tmux.conf

rm -rf ~/.config
ln -fs ~/.sys-config/config/  ~/.config
